# Generated by Django 3.2.12 on 2022-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_iplmatchesplayedvswon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipltopeconomicalbowlers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('topeconomybowler', models.CharField(max_length=40)),
                ('teamname', models.CharField(max_length=4)),
                ('matches', models.IntegerField()),
                ('economy', models.IntegerField()),
            ],
        ),
    ]
